USE CGV;

DROP PROCEDURE IF EXISTS MEMBER_MOVIE_COUNT;
DELIMITER //
CREATE PROCEDURE MEMBER_MOVIE_COUNT(
	IN _ID VARCHAR(20)
)
BEGIN
	-- 지역 변수 선언은 위에 모아줘야 함. 
	DECLARE _MOVIE_COUNT INT DEFAULT 0;
    
	WITH TICKETING_COUNT(SS_MO_NUM, MOVIE_TICKETING_COUNT)
		AS
		(SELECT SS_MO_NUM, COUNT(*) FROM ticketing
			JOIN screen_schedule ON TI_SS_NUM = SS_NUM
			WHERE TI_ME_ID LIKE _ID
			GROUP BY SS_MO_NUM) -- 영화별 예매 횟수, 예매한 전체 영화 수가 아님 
		SELECT @NUM := COUNT(*) FROM TICKETING_COUNT;
	SET _MOVIE_COUNT = (SELECT @NUM);
	UPDATE MEMBER SET ME_MOVIE_COUNT = _MOVIE_COUNT WHERE ME_ID = _ID;
END //
DELIMITER ;
CALL MEMBER_MOVIE_COUNT('abc');