-- 예매를 취소했을 때 예매 가능 좌석을 수정하는 트리거를 추가하고, 확인하세요. 
USE CGV;
DROP TRIGGER IF EXISTS DELETE_TICKETING;

DELIMITER //
CREATE TRIGGER DELETE_TICKETING BEFORE DELETE
ON TICKETING
FOR EACH ROW
BEGIN
	-- 예매된 좌석을 삭제 
	DELETE FROM TICKETING_SEAT WHERE TS_TI_NUM = OLD.TI_NUM;
    -- 예매 가능 좌석수를 증가 
	UPDATE SCREEN_SCHEDULE SET SS_POSSIBLE_SEAT = SS_POSSIBLE_SEAT + OLD.TI_AMOUNT
		WHERE SS_NUM = OLD.TI_SS_NUM;
	-- CALL MEMBER_MOVIE_COUNT(OLD.TI_ME_ID);
END //
DELIMITER ;
DELETE FROM TICKETING WHERE TI_NUM = 1;
