-- 예매를 하면, 해당 영화상영시간의 예매 가능 좌석을 수정해주는 트리거를 생성하고, 테스트해보세요. 
-- TICKETING 테이블에 데이터가 추가 되면 트리거 동작 
USE CGV;
DROP TRIGGER IF EXISTS INSERT_TICKETING;

DELIMITER //
CREATE TRIGGER INSERT_TICKETING AFTER INSERT
ON TICKETING
FOR EACH ROW
BEGIN
UPDATE SCREEN_SCHEDULE 
	SET SS_POSSIBLE_SEAT = SS_POSSIBLE_SEAT - NEW.TI_AMOUNT
WHERE SS_NUM = NEW.TI_SS_NUM;
END //
DELIMITER ;
INSERT INTO TICKETING(TI_AMOUNT, TI_ME_ID, TI_SS_NUM, TI_TOTAL_PRICE)
VALUES(1, 'abc', 26, 10000);